"""initial_schema_10_tables

Revision ID: 2dec2aa2d41a
Revises: 
Create Date: 2026-08-23 14:12:58.652631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2dec2aa2d41a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('model_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('WARMING_UP', 'ACTIVE', 'DEPRECATED', name='model_status_enum'), server_default='warming_up', nullable=False),
    sa.Column('baseline_f1', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('baseline_auc', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('prediction_type', sa.Enum('BINARY', 'MULTICLASS', 'REGRESSION', name='prediction_type_enum'), nullable=False),
    sa.Column('sample_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('deprecated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status != 'deprecated' OR deprecated_at IS NOT NULL", name='ck_models_deprecated_has_timestamp'),
    sa.CheckConstraint('baseline_auc IS NULL OR (baseline_auc >= 0 AND baseline_auc <= 1)', name='ck_models_baseline_auc_range'),
    sa.CheckConstraint('baseline_f1 IS NULL OR (baseline_f1 >= 0 AND baseline_f1 <= 1)', name='ck_models_baseline_f1_range'),
    sa.CheckConstraint('deprecated_at IS NULL OR deprecated_at >= registered_at', name='ck_models_deprecated_after_registered'),
    sa.CheckConstraint('sample_count >= 0', name='ck_models_sample_count_non_negative'),
    sa.PrimaryKeyConstraint('model_id'),
    sa.UniqueConstraint('name', 'version', name='uq_models_name_version')
    )
    op.create_table('alerts',
    sa.Column('alert_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('DRIFT', 'SCHEMA_VIOLATION', 'SCHEMA_WARNING', 'PERFORMANCE_DEGRADATION', 'LOG_ANOMALY', 'TRIGGER_FAILURE', 'MONITORING_ENGINE_FAILURE', name='alert_type_enum'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alert_severity_enum'), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=True),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('context_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('resolved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(resolved = false AND resolved_at IS NULL) OR (resolved = true AND resolved_at IS NOT NULL)', name='ck_alerts_resolved_consistency'),
    sa.CheckConstraint('cooldown_until IS NULL OR cooldown_until > triggered_at', name='ck_alerts_cooldown_after_triggered'),
    sa.CheckConstraint('resolved_at IS NULL OR resolved_at >= triggered_at', name='ck_alerts_resolved_after_triggered'),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index('idx_alerts_cooldown', 'alerts', ['model_id', 'type', 'feature_name', 'cooldown_until'], unique=False, postgresql_where=sa.text('resolved = false'))
    op.create_index('idx_alerts_model_unresolved', 'alerts', ['model_id', sa.text('severity DESC'), sa.text('triggered_at DESC')], unique=False, postgresql_where=sa.text('resolved = false'))
    op.create_table('drift_reports',
    sa.Column('report_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('PSI', 'CHI_SQUARE', name='drift_method_enum'), nullable=False),
    sa.Column('score', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('p_value', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('feature_type', sa.Enum('NUMERICAL', 'CATEGORICAL', name='feature_type_enum'), nullable=False),
    sa.Column('psi', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("(method = 'chi_square' AND p_value IS NOT NULL) OR (method = 'psi' AND p_value IS NULL)", name='ck_drift_reports_method_p_value'),
    sa.CheckConstraint('p_value IS NULL OR (p_value >= 0 AND p_value <= 1)', name='ck_drift_reports_p_value_range'),
    sa.CheckConstraint('sample_count >= 30', name='ck_drift_reports_sample_count_min'),
    sa.CheckConstraint('score >= 0', name='ck_drift_reports_score_non_negative'),
    sa.CheckConstraint('window_start < window_end', name='ck_drift_reports_window_order'),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index('idx_drift_model_computed', 'drift_reports', ['model_id', sa.text('computed_at DESC')], unique=False)
    op.create_table('log_classifications',
    sa.Column('log_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('log_line', sa.String(length=2000), nullable=False),
    sa.Column('label', sa.Enum('ANOMALOUS', 'NORMAL', name='log_label_enum'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('model_checkpoint', sa.String(length=100), nullable=False),
    sa.Column('alert_created', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('classified_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("alert_created = false OR label = 'anomalous'", name='ck_log_classifications_alert_only_anomalous'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_log_classifications_confidence_range'),
    sa.CheckConstraint('length(log_line) >= 10 AND length(log_line) <= 2000', name='ck_log_classifications_log_line_length'),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('idx_logclass_model_anomalous', 'log_classifications', ['model_id', sa.text('classified_at DESC')], unique=False, postgresql_where=sa.text("label = 'anomalous'"))
    op.create_table('model_schemas',
    sa.Column('schema_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('dtype', sa.Enum('FLOAT', 'INT', 'BOOL', 'STRING', 'CATEGORY', name='feature_dtype_enum'), nullable=False),
    sa.Column('required', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('min_value', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('max_length', sa.SmallInteger(), nullable=True),
    sa.Column('allowed_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("(dtype IN ('float', 'int') AND allowed_values IS NULL AND max_length IS NULL) OR (dtype = 'category' AND max_length IS NULL) OR (dtype = 'string') OR (dtype = 'bool' AND max_length IS NULL AND min_value IS NULL AND max_value IS NULL)", name='ck_model_schemas_dtype_constraints'),
    sa.CheckConstraint('max_length IS NULL OR (max_length >= 1 AND max_length <= 1000)', name='ck_model_schemas_max_length_range'),
    sa.CheckConstraint('min_value IS NULL OR max_value IS NULL OR min_value < max_value', name='ck_model_schemas_min_lt_max'),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schema_id'),
    sa.UniqueConstraint('model_id', 'feature_name', name='uq_model_schemas_model_feature')
    )
    op.create_table('performance_logs',
    sa.Column('perf_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric', sa.Enum('F1', 'AUC', name='performance_metric_enum'), nullable=False),
    sa.Column('value', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('baseline_value', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('delta', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('baseline_value >= 0 AND baseline_value <= 1', name='ck_perf_logs_baseline_range'),
    sa.CheckConstraint('delta >= -1 AND delta <= 1', name='ck_perf_logs_delta_range'),
    sa.CheckConstraint('sample_count >= 50', name='ck_perf_logs_sample_count_min'),
    sa.CheckConstraint('value >= 0 AND value <= 1', name='ck_perf_logs_value_range'),
    sa.CheckConstraint('window_start < window_end', name='ck_perf_logs_window_order'),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('perf_id')
    )
    op.create_table('predictions',
    sa.Column('pred_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('features_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prediction_label', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('schema_valid', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('window_bucket', sa.DateTime(timezone=True), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_predictions_confidence_range'),
    sa.CheckConstraint('length(prediction_label) >= 1 AND length(prediction_label) <= 50', name='ck_predictions_label_length'),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('pred_id')
    )
    op.create_index('idx_predictions_model_logged', 'predictions', ['model_id', sa.text('logged_at DESC')], unique=False)
    op.create_index('idx_predictions_model_window', 'predictions', ['model_id', sa.text('window_bucket DESC')], unique=False)
    op.create_index('idx_predictions_schema_valid', 'predictions', ['model_id', 'schema_valid'], unique=False, postgresql_where=sa.text('schema_valid = false'))
    op.create_table('reference_stats',
    sa.Column('stat_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('stat_type', sa.Enum('MEAN', 'STD', 'MIN', 'MAX', 'P25', 'P50', 'P75', 'P95', 'FREQUENCY_MAP', 'HISTOGRAM_BIN_EDGES', 'HISTOGRAM_COUNTS', name='stat_type_enum'), nullable=False),
    sa.Column('stat_value', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('frequency_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('histogram_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("(stat_type = 'frequency_map' AND frequency_map IS NOT NULL AND stat_value IS NULL AND histogram_data IS NULL) OR (stat_type IN ('histogram_bin_edges', 'histogram_counts') AND histogram_data IS NOT NULL AND stat_value IS NULL AND frequency_map IS NULL) OR (stat_type NOT IN ('frequency_map', 'histogram_bin_edges', 'histogram_counts') AND stat_value IS NOT NULL AND frequency_map IS NULL AND histogram_data IS NULL)", name='ck_reference_stats_stat_type_exclusivity'),
    sa.CheckConstraint('sample_count >= 30', name='ck_reference_stats_sample_count_min'),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stat_id'),
    sa.UniqueConstraint('model_id', 'feature_name', 'stat_type', name='uq_reference_stats_model_feature_stat')
    )
    op.create_table('trigger_events',
    sa.Column('trigger_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'SUPPRESSED', name='trigger_status_enum'), nullable=False),
    sa.Column('drift_report_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('github_response_code', sa.SmallInteger(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('error_type', sa.String(length=64), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('next_allowed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(status = 'success' AND github_response_code = 204 AND error_message IS NULL AND error_type IS NULL) OR (status = 'failed' AND github_response_code IS NOT NULL AND error_message IS NOT NULL AND error_type IS NULL) OR (status = 'failed' AND github_response_code IS NULL AND error_message IS NOT NULL AND error_type IN ('NETWORK_TIMEOUT', 'DNS_FAILURE', 'CONNECTION_REFUSED')) OR (status = 'suppressed' AND github_response_code IS NULL AND error_type IS NULL)", name='ck_trigger_status_consistency'),
    sa.CheckConstraint('next_allowed_at > triggered_at', name='ck_trigger_next_after_triggered'),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('trigger_id')
    )
    op.create_index('idx_trigger_model_cooldown', 'trigger_events', ['model_id', sa.text('next_allowed_at DESC')], unique=False)
    op.create_table('ground_truth',
    sa.Column('gt_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('pred_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('true_label', sa.String(length=50), nullable=False),
    sa.Column('latency_hours', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('latency_hours >= 0', name='ck_ground_truth_latency_non_negative'),
    sa.CheckConstraint('length(true_label) >= 1 AND length(true_label) <= 50', name='ck_ground_truth_label_length'),
    sa.ForeignKeyConstraint(['pred_id'], ['predictions.pred_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('gt_id'),
    sa.UniqueConstraint('pred_id')
    )
    op.create_index('idx_gt_model_received', 'ground_truth', ['model_id', sa.text('received_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_gt_model_received', table_name='ground_truth')
    op.drop_table('ground_truth')
    op.drop_index('idx_trigger_model_cooldown', table_name='trigger_events')
    op.drop_table('trigger_events')
    op.drop_table('reference_stats')
    op.drop_index('idx_predictions_schema_valid', table_name='predictions', postgresql_where=sa.text('schema_valid = false'))
    op.drop_index('idx_predictions_model_window', table_name='predictions')
    op.drop_index('idx_predictions_model_logged', table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('performance_logs')
    op.drop_table('model_schemas')
    op.drop_index('idx_logclass_model_anomalous', table_name='log_classifications', postgresql_where=sa.text("label = 'anomalous'"))
    op.drop_table('log_classifications')
    op.drop_index('idx_drift_model_computed', table_name='drift_reports')
    op.drop_table('drift_reports')
    op.drop_index('idx_alerts_model_unresolved', table_name='alerts', postgresql_where=sa.text('resolved = false'))
    op.drop_index('idx_alerts_cooldown', table_name='alerts', postgresql_where=sa.text('resolved = false'))
    op.drop_table('alerts')
    op.drop_table('models')
    # ### end Alembic commands ###
